# Name of action
name: CI/CD to Vultr

on:
  push:
    branches: [production]

jobs:
  Setup:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [12.18.4]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
        env:
          CI: true

  deploy:
    runs-on: ubuntu-latest
    needs: Setup
    if: github.ref == 'refs/heads/production'
    steps:
      - name: Deploying to Vultr
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.PATH }}
            git pull
            npm prune
            npm ci
            pm2 reload 5
